per-item-permissions: false
ranks:
  Default:
    cost: 20
    cooldown:
      one: 240
      all: 480
  Builder:
    cost: 15
    cooldown:
      one: 120
      all: 240
  Admin:
    cost: 10
    cooldown:
      one: 60
      all: 120
  Owner:
    cost: 5
    cooldown:
      one: 30
      all: 60
      
smeltable-items:
  - PORKCHOP
  - BEEF
  - CHICKEN
  - COD
  - SALMON
  - POTATO
  - MUTTON
  - RABBIT
  - IRON_ORE
  - GOLD_ORE
  - NETHER_GOLD_ORE
  - SAND
  - RED_SAND
  - SANDSTONE
  - RED_SANDSTONE
  - QUARTZ_BLOCK
  - COBBLESTONE
  - STONE
  - CLAY_BALL
  - NETHERRACK
  - CLAY
  - STONE_BRICKS
  - INFESTED_STONE_BRICKS
  - NETHER_BRICKS
  - POLISHED_BLACKSTONE_BRICKS
  - DIAMOND_ORE
  - LAPIS_ORE
  - REDSTONE_ORE
  - COAL_ORE
  - COPPER_ORE
  - EMERALD_ORE
  - NETHER_QUARTZ_ORE
  - OAK_LOG
  - SPRUCE_LOG
  - BIRCH_LOG
  - JUNGLE_LOG
  - ACACIA_LOG
  - DARK_OAK_LOG
  - STRIPPED_OAK_LOG
  - STRIPPED_SPRUCE_LOG
  - STRIPPED_BIRCH_LOG
  - STRIPPED_JUNGLE_LOG
  - STRIPPED_ACACIA_LOG
  - STRIPPED_DARK_OAK_LOG
  - OAK_WOOD
  - SPRUCE_WOOD
  - BIRCH_WOOD
  - JUNGLE_WOOD
  - ACACIA_WOOD
  - DARK_OAK_WOOD
  - STRIPPED_OAK_WOOD
  - STRIPPED_SPRUCE_WOOD
  - STRIPPED_BIRCH_WOOD
  - STRIPPED_JUNGLE_WOOD
  - STRIPPED_ACACIA_WOOD
  - STRIPPED_DARK_OAK_WOOD
  - CACTUS
  - WET_SPONGE
  - CHORUS_FRUIT
  - ANCIENT_DEBRIS
  - WHITE_TERRACOTTA
  - ORANGE_TERRACOTTA
  - MAGENTA_TERRACOTTA
  - LIGHT_BLUE_TERRACOTTA
  - YELLOW_TERRACOTTA
  - LIME_TERRACOTTA
  - PINK_TERRACOTTA
  - GRAY_TERRACOTTA
  - LIGHT_GRAY_TERRACOTTA
  - CYAN_TERRACOTTA
  - PURPLE_TERRACOTTA
  - BLUE_TERRACOTTA
  - BROWN_TERRACOTTA
  - GREEN_TERRACOTTA
  - RED_TERRACOTTA
  - BLACK_TERRACOTTA
  - KELP